#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.170:3306/elco_zhuchi_system?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: toor
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.0.170
#    port: 6379
#    password: root123redis
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 100MB
#      max-request-size: 100MB
#  feign:
#    httpclient:
#      enabled: false
#    okhttp:
#      enabled: true
#ribbon:
#  ConnectTimeout: 5000
#  ReadTimeout: 10000
#min:
#  io:
#    endpoint: 192.168.0.170
#    port: 30200
#    accessKey: minio12345
#    secretKey: minio12345
#    secure: false
#swagger:
#  title: 系统平台-资源中心微服务
#harbor:
#  url: http://10.36.31.157:8802
#  username: admin
#  password: Harbor12345
#xxl:
#  job:
#    accessToken: xxl5320job
#    admin:
#      addresses: http://192.168.0.170:8092/xxl-job-admin
#    executor:
#      appName: elco-zhuchi-scheduled-center
#      logpath: /data/applogs/xxl-job/serverhandler
#      logRetentionDays: 30